services:
  - name: gin-google-sheets-api
    type: web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
